Serilog:
  Using: [ "Serilog.Sinks.Console", "Serilog.Sinks.Loki" ]
  MinimumLevel:
    Default: Information
    Override:
      SS14: Debug
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: Warning

  WriteTo:
    - Name: Console
      Args:
        Theme: Serilog.Sinks.SystemConsole.Themes.AnsiConsoleThemes::Code, Serilog.Sinks.Console
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]

  #Loki:
  #  Address: "http://localhost:3100"
  #  Name: "Test"
urls: "http://localhost:45896"
Changelog:
  # Secret configured in the github webhook, to ensure authenticity.
  GitHubSecret: "6924#NTBox!"
  # The branch to look at for generating changelogs.
  ChangelogBranchName: "master"
  # File in Resources/Changelog/ that will be updated.
  ChangelogFilename: "Changelog.yml"
  # The SSH Key to use to push/pull changes.
  SshKey: '/root/changelog_key'
  # The on-disk repo to keep up to date and to generate changelogs in.
  # You need to initialize this manually with git clone.
  ChangelogRepo: '/root/qds/Que_Delicia_Station_14/Resources/Changelog'
  # How long to wait after a changelog-change has been merged/pushed before we generate changelogs and push a commit.
  DelaySeconds: 60

AllowedHosts: "*"
